version: '3.7'

services:
  julioperez-database:
    container_name: julioperez-database
    image: postgres
    environment:
      POSTGRES_USER: julioperezdev
      POSTGRES_PASSWORD: openSourcePassword
      PGDATA: /data/postgres
      POSTGRES_DB: julioperez
    volumes:
      - ./database:/data/postgres
    ports:
      - "25432:5432"
    restart: unless-stopped