version: '3.7'

services:
  julioperez-database:
    container_name: julioperez-database
    image: viloria/julioperez-db:v1
    volumes:
      - ./database/data:/pgdata
    ports:
      - "25432:5432"
    restart: unless-stopped
