-- Auth schema

CREATE SCHEMA IF NOT EXISTS AUTH;

CREATE TABLE IF NOT EXISTS AUTH.USER_ROL (
    ID VARCHAR(255) NOT NULL,
	DESCRIPTION VARCHAR(255) NOT NULL UNIQUE,
    PRIMARY KEY (ID)
);

INSERT INTO AUTH.USER_ROL(ID, DESCRIPTION) VALUES ('8b98a829-a1a4-4690-8ba4-bf0126276431', 'USER');


-- Certificate schema

CREATE SCHEMA IF NOT EXISTS CERTIFICATE;


